### ISSUE TITLE
Get Token from Async Store

### ISSUE THREAD

**Issue by skyler2440** [Lambda-School-Labs/net-giver-work-order-management-fe#27]
# What is done

- Token is saved to AsyncStorage in /screens/Login/LoginVerify.js
- Token is console logging from AsyncStorage in /WorkOrder/WorkOrderListView.js

# What needs to be done 

## Checkout to branch/create new branch async-token

- [x] Each page with a GQL call needs to get token from asyncStore and successfully use it in the GQL call

**Comment by skylerwebdev** [comment]
Done Token is being stored in context and async
